name: Deploy to Server

on:
  push:
    branches:
      - main  # hoặc tên branch chính của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.0'  # Chọn phiên bản Python phù hợp với dự án của bạn

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Nếu bạn có file requirements.txt

    - name: Deploy to server
      env:
        DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}
      run: |
        curl -X POST $DEPLOY_HOOK_URL
